export const PRODUCTS = [
  {
    id: 1,
    title: "iPhone 9",
    price: 549,
    stock: 4,
    brand: "Apple",
  },
  {
    id: 2,
    title: "iPhone X",
    price: 899,
    stock: 4,
    brand: "Apple",
  },
  {
    id: 3,
    title: "Samsung Universe 9",
    price: 1249,
    stock: 6,
    brand: "Samsung",
  },
  {
    id: 4,
    title: "OPPOF19",
    price: 280,
    stock: 3,
    brand: "OPPO",
  },
  {
    id: 5,
    title: "Huawei P30",
    price: 499,
    stock: 2,
    brand: "Huawei",
  },
  {
    id: 6,
    title: "MacBook Pro",
    price: 1749,
    stock: 3,
    brand: "Apple",
  },
  {
    id: 7,
    title: "Samsung Galaxy Book",
    price: 1499,
    discountPercentage: 4.15,
    stock: 1,
    brand: "Samsung",
  },
  {
    id: 8,
    title: "Microsoft Surface Laptop 4",
    price: 1499,
    stock: 2,
    brand: "Microsoft Surface",
  },
  {
    id: 9,
    title: "Infinix INBOOK",
    price: 1099,
    stock: 1,
    brand: "Infinix",
  },
  {
    id: 10,
    title: "HP Pavilion 15-DK1056WM",
    price: 1099,
    stock: 1,
    brand: "HP Pavilion",
  },
];
